"""Aplica la piel SCOUTER sobre el index.html generado por generar_html.py."""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, 'index.html')

CSS = r'''
:root{--bg:#101814;--surface:#17201b;--surface2:#1d2821;--card:#18211c;--line:#2a352d;--green:#66c34d;--text:#f1f5ef;--muted:#89948c;--soft:#b8c0ba;--gold:#f5c744;--red:#e95b59}
*{box-sizing:border-box}html,body{background:var(--bg)!important;color:var(--text)!important;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif!important}body{max-width:760px;margin:auto!important;padding:0 0 88px!important}
.folder-tab,body>header,body>.indice,footer{display:none!important}
.sc-header{position:sticky;top:0;z-index:50;background:linear-gradient(180deg,#2c4b29,#17231b 88%);padding:18px 16px 10px;border-radius:0 0 24px 24px;box-shadow:0 8px 30px #0006}.sc-brand{display:flex;align-items:center;justify-content:space-between}.sc-logo{font-size:28px;font-weight:900;font-style:italic;letter-spacing:1px}.sc-logo em{font-style:normal;color:var(--green)}.sc-actions{display:flex;gap:7px}.sc-pill{border:1px solid #ffffff20;background:#ffffff18;border-radius:22px;padding:9px 12px;font-weight:800}.sc-vip{background:var(--gold);color:#10130f;border:0}.sc-search{width:100%;margin-top:14px;background:#0d140f;border:1px solid #ffffff12;border-radius:12px;padding:11px 13px;color:#fff;outline:0}.sc-tabs{display:flex;gap:26px;overflow:auto;padding:13px 14px 4px;background:var(--bg);scrollbar-width:none}.sc-tabs button{white-space:nowrap;color:var(--muted);border:0;background:none;padding:5px 0 9px;font-weight:800}.sc-tabs button.active{color:#fff;border-bottom:3px solid var(--green)}
.top5-section{margin:12px;border:1px solid var(--line)!important;border-radius:14px;background:#151f19!important;padding:10px 12px 14px!important}.top5-section .section-label{font-family:inherit!important;color:var(--muted)!important}.top5-item{display:grid!important;grid-template-columns:34px 1fr!important;gap:8px!important;padding:12px 0!important;border-bottom:1px solid var(--line)!important}.top5-rank{font-family:inherit!important;color:var(--green)!important;font-weight:900}.top5-partido{font-family:inherit!important;font-size:12px!important}.top5-mercado{color:var(--green)!important;font-size:11px!important}.top5-justif{color:var(--soft)!important;font-size:10px!important}.top5-meta{color:var(--muted)!important;font-family:inherit!important;font-size:9px!important}.ev-calc{background:#0f1712!important;border-color:var(--line)!important}.ev-input{background:#111913!important;color:#fff!important;border-color:var(--line)!important}
.liga-section{padding:0 12px 8px!important;border:0!important}.liga-header{background:#121b16;border:1px solid var(--line);border-radius:13px;padding:14px 15px;margin:8px 0 9px!important}.liga-titulo{font-family:inherit!important;font-size:15px!important;font-weight:800;color:#fff}.liga-count{font-family:inherit!important;color:var(--muted)!important;font-size:10px}.match-card{background:linear-gradient(180deg,#1c2920,#162019)!important;border:1px solid #26342b!important;border-radius:13px!important;margin:0 0 10px!important;overflow:hidden!important;box-shadow:0 5px 16px #0003}.match-card summary{padding:0!important;list-style:none!important}.match-card summary::-webkit-details-marker{display:none}.match-teams{font-family:inherit!important;font-size:14px!important;font-weight:800}.match-meta{font-family:inherit!important;color:var(--muted)!important;font-size:9px!important}.match-card summary:before{content:'⚽';float:left;margin:14px 9px 0 12px;color:var(--green);font-size:13px}.match-body{padding:13px!important;border-top:1px solid var(--line)!important;background:#121a15}.section-label{font-family:inherit!important;color:var(--muted)!important;font-size:9px!important;letter-spacing:1.2px!important}.sello{font-family:inherit!important;color:var(--green)!important;border-color:#66c34d66!important;transform:none!important}.sello.pendiente{color:var(--gold)!important;border-color:#f5c74455!important}.pick-destacado{background:linear-gradient(135deg,#1d3320,#17241b)!important;border:1px solid #4f8e4266;border-radius:13px!important;color:#fff!important}.pick-destacado .valor{font-family:inherit!important;font-size:16px!important;font-weight:900}.pick-destacado .fundamento{color:var(--soft)!important}.redactado{background:#0e1510!important;color:var(--muted)!important;border:1px dashed #344039}.comp-grid{gap:7px}.stat-box{background:#0e1611!important;border-color:var(--line)!important}.stat-val{color:var(--green)!important}.evento-ficha{border-color:var(--line)!important;color:var(--soft)!important}.ev-resultado{color:var(--green)}
.sc-pick-line{display:flex;align-items:center;justify-content:space-between;padding:9px 12px;background:#0f1712;border-top:1px solid var(--line);border-bottom:1px solid var(--line);font-size:11px}.sc-pick-line b{color:var(--green)}.sc-odds{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;padding:9px 12px}.sc-odd{background:#111913;border:1px solid #263229;border-radius:8px;text-align:center;padding:7px}.sc-odd span{display:block;color:var(--muted);font-size:9px}.sc-odd b{font-size:13px}.sc-star{float:right;margin:10px 12px 0 0;font-size:22px;color:#d7ded8}.sc-star.on{color:var(--gold)}
.sc-bottom{position:fixed;bottom:0;left:50%;transform:translateX(-50%);width:min(760px,100%);height:74px;background:#151d18f7;backdrop-filter:blur(14px);border-top:1px solid #2a342d;display:grid;grid-template-columns:repeat(5,1fr);z-index:60}.sc-bottom button{background:none;border:0;color:var(--muted);font-size:9px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px}.sc-bottom button.active{color:#fff}.sc-bottom i{font-style:normal;font-size:21px}.sc-bottom button.active i{color:var(--green)}
@media(max-width:420px){.sc-tabs{gap:22px}.match-teams{font-size:13px}}
.match-card[open]{position:fixed!important;inset:0!important;z-index:100!important;margin:0!important;border-radius:0!important;overflow:auto!important;background:var(--bg)!important}.match-card[open] summary{position:sticky;top:0;z-index:5;background:#121b16!important;padding:16px 14px!important;border-bottom:1px solid var(--line)}.match-card[open] summary:before{content:'‹';font-size:32px;margin:0 12px 0 0;line-height:20px}.match-card[open] .match-body{min-height:calc(100vh - 80px);padding:15px!important}.match-card[open] .sc-detail-tabs{display:flex}.sc-detail-tabs{display:none;position:sticky;top:69px;z-index:4;gap:4px;overflow:auto;background:#151e19;border-bottom:1px solid var(--line);padding:0 8px}.sc-detail-tabs button{white-space:nowrap;background:none;border:0;color:var(--muted);padding:13px 12px;font-size:10px;font-weight:800}.sc-detail-tabs button.active{color:#fff;border-bottom:3px solid var(--green)}.sc-detail-panel{display:block}.sc-detail-panel.hidden{display:none}
'''

JS = r'''
(function(){
  const qs=(s,c=document)=>c.querySelector(s), qsa=(s,c=document)=>[...c.querySelectorAll(s)];
  const key='scouter_favs'; let favs=JSON.parse(localStorage.getItem(key)||'[]');
  const app=document.createElement('div'); app.className='sc-header'; app.innerHTML=`<div class="sc-brand"><div class="sc-logo">SCOUT<em>ER</em></div><div class="sc-actions"><button class="sc-pill">◌</button><button class="sc-pill">$</button><button class="sc-pill sc-vip">♛ VIP</button></div></div><input class="sc-search" id="sc-search" placeholder="Buscar equipo o partido...">`;
  document.body.prepend(app);
  const tabs=document.createElement('nav'); tabs.className='sc-tabs'; tabs.innerHTML='<button class="active" data-filter="all">Ganador</button><button data-filter="goals">Más/Menos 2.5</button><button data-filter="first">Ganador 1er Tiempo</button><button data-filter="btts">Ambos Anotan</button><button data-filter="smart">Apuesta inteligente</button>'; app.after(tabs);
  qsa('.match-card').forEach((card,i)=>{
    const id=String(i+1); card.dataset.scId=id;
    const summary=qs('summary',card); if(!summary)return;
    const badge=qs('.pick-destacado .valor',card)?.textContent?.trim() || 'Apuesta inteligente';
    const prob=(qs('.pick-destacado .tag',card)?.textContent||'').match(/probabilidad propia\s*([\d.,]+)/i)?.[1] || '';
    const line=document.createElement('div'); line.className='sc-pick-line'; line.innerHTML=`<span>✓ ${badge}</span><b>${prob?prob+'%':'—'}</b>`; summary.after(line);
    const calc=card.querySelector('.ev-calc'); if(calc)calc.style.display='none';
    const star=document.createElement('button'); star.className='sc-star'; star.textContent=favs.includes(id)?'★':'☆'; star.classList.toggle('on',favs.includes(id)); star.onclick=e=>{e.preventDefault();e.stopPropagation();toggleFav(id,star)}; summary.appendChild(star);
    const body=qs('.match-body',card); if(body){ const labels=qsa('.section-label',body); const dt=document.createElement('div'); dt.className='sc-detail-tabs'; dt.innerHTML='<button class="active">RESUMEN</button><button>PREDICCIONES</button><button>CUOTAS</button><button>ESTADÍSTICAS</button>'; body.prepend(dt); const panels=labels.map(l=>l.nextElementSibling).filter(Boolean); qsa('.sc-detail-tabs button',dt).forEach((b,j)=>b.onclick=e=>{e.stopPropagation();qsa('.sc-detail-tabs button',dt).forEach(x=>x.classList.remove('active'));b.classList.add('active'); if(j===0){panels.forEach(x=>x.classList.remove('hidden'));} else {panels.forEach(x=>x.classList.add('hidden')); const want=j===1?'pick más seguro':j===2?'mercado principal':'historial calculado'; labels.forEach((lab,k)=>{if((lab.textContent||'').toLowerCase().includes(want)&&panels[k])panels[k].classList.remove('hidden')})}}); }
  });
  function toggleFav(id,star){ const n=favs.indexOf(id); if(n>=0)favs.splice(n,1); else favs.push(id); localStorage.setItem(key,JSON.stringify(favs)); star.textContent=favs.includes(id)?'★':'☆'; star.classList.toggle('on',favs.includes(id)); }
  function filter(mode){ const q=(qs('#sc-search').value||'').toLowerCase(); qsa('.match-card').forEach(c=>{let ok=c.innerText.toLowerCase().includes(q); const t=c.innerText.toLowerCase(); if(mode==='goals')ok=ok&&(t.includes('más')||t.includes('menos')||t.includes('goles')); if(mode==='first')ok=ok&&t.includes('primer'); if(mode==='btts')ok=ok&&t.includes('ambos'); if(mode==='smart')ok=ok&&!t.includes('ganador'); c.style.display=ok?'':'none'}); qsa('.liga-section').forEach(s=>s.style.display=qsa('.match-card',s).some(c=>c.style.display!=='none')?'':'none'); }
  qsa('.sc-tabs button').forEach(b=>b.onclick=()=>{qsa('.sc-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter(b.dataset.filter)}); qs('#sc-search').oninput=()=>filter(qs('.sc-tabs button.active').dataset.filter);
  const nav=document.createElement('nav'); nav.className='sc-bottom'; nav.innerHTML='<button class="active"><i>⚽</i>Ligas</button><button><i>♨</i>Consejos VIP</button><button><i>♙</i>Equipos</button><button><i>▣</i>En vivo</button><button><i>☆</i>Favoritos</button>'; document.body.appendChild(nav);
  const nb=qsa('button',nav); nb.forEach((b,i)=>b.onclick=()=>{nb.forEach(x=>x.classList.remove('active'));b.classList.add('active'); if(i===0){filter('all');window.scrollTo({top:0,behavior:'smooth'});} if(i===1){qs('.top5-section')?.scrollIntoView({behavior:'smooth'});} if(i===2){alert('Equipos: próximamente conectado a la base de equipos.');} if(i===3){qsa('.match-card').forEach(c=>c.style.display=c.innerText.toLowerCase().includes('en vivo')?'':'none');} if(i===4){qsa('.match-card').forEach(c=>c.style.display=favs.includes(c.dataset.scId)?'':'none');}});
})();
'''

with open(INDEX, encoding='utf-8') as f:
    doc=f.read()
style='<style id="scouter-skin">/* SCOUTER_SKIN */\n'+CSS+'\n</style>'
script='<script id="scouter-skin-js">'+JS+'\n</script>'
if 'id="scouter-skin"' not in doc: doc=doc.replace('</head>',style+'\n</head>')
if 'id="scouter-skin-js"' not in doc: doc=doc.replace('</body>',script+'\n</body>')
with open(INDEX,'w',encoding='utf-8') as f:f.write(doc)
print('SCOUTER skin applied')
